#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IMSARTK2")]
public partial class LargeDatabaseDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public LargeDatabaseDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["IMSART_0311ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public LargeDatabaseDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LargeDatabaseDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LargeDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public LargeDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<V_FACT> V_FACTs
	{
		get
		{
			return this.GetTable<V_FACT>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_FACT")]
public partial class V_FACT
{
	
	private System.Nullable<int> _IMYEAR;
	
	private System.Nullable<int> _IMMONTH;
	
	private string _BPOINT;
	
	private string _EPOINT;
	
	private string _ADD_;
	
	private int _FCT_ID;
	
	private string _FCT_TRAINNO;
	
	private string _FCT_SUBCODE;
	
	private string _FCT_NO;
	
	private string _FCT_CONTAINERNO;
	
	private System.Nullable<double> _FCT_WEIGHT;
	
	private string _FCT_OVERHEAD;
	
	private System.Nullable<System.DateTime> _FCT_IMDATE;
	
	private System.Nullable<System.DateTime> _FCT_EXDATE;
	
	private System.Nullable<System.TimeSpan> _FCT_IMTIME;
	
	private System.Nullable<System.TimeSpan> _FCT_EXTIME;
	
	private System.Nullable<int> _FCT_STATUS;
	
	private System.Nullable<System.DateTime> _FCT_LOADDATE;
	
	private string _FCT_QNQ;
	
	private string _FCT_ETSNG;
	
	private string _RT_NAME;
	
	private string _NAME1;
	
	private string _USERNAME;
	
	private string _USERNAME_N;
	
	private string _BORDER;
	
	private string _CLC_ALLNAME;
	
	private string _type;
	
	private string _STATUS_;
	
	private string _FILE1;
	
	private string _FRM_NAME;
	
	private string _FCT_CONTROL;
	
	private string _B_NAME1;
	
	public V_FACT()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMYEAR", DbType="Int")]
	public System.Nullable<int> IMYEAR
	{
		get
		{
			return this._IMYEAR;
		}
		set
		{
			if ((this._IMYEAR != value))
			{
				this._IMYEAR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMMONTH", DbType="Int")]
	public System.Nullable<int> IMMONTH
	{
		get
		{
			return this._IMMONTH;
		}
		set
		{
			if ((this._IMMONTH != value))
			{
				this._IMMONTH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BPOINT", DbType="NVarChar(301)")]
	public string BPOINT
	{
		get
		{
			return this._BPOINT;
		}
		set
		{
			if ((this._BPOINT != value))
			{
				this._BPOINT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EPOINT", DbType="NVarChar(301)")]
	public string EPOINT
	{
		get
		{
			return this._EPOINT;
		}
		set
		{
			if ((this._EPOINT != value))
			{
				this._EPOINT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADD_", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
	public string ADD_
	{
		get
		{
			return this._ADD_;
		}
		set
		{
			if ((this._ADD_ != value))
			{
				this._ADD_ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_ID", DbType="Int NOT NULL")]
	public int FCT_ID
	{
		get
		{
			return this._FCT_ID;
		}
		set
		{
			if ((this._FCT_ID != value))
			{
				this._FCT_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_TRAINNO", DbType="VarChar(50)")]
	public string FCT_TRAINNO
	{
		get
		{
			return this._FCT_TRAINNO;
		}
		set
		{
			if ((this._FCT_TRAINNO != value))
			{
				this._FCT_TRAINNO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_SUBCODE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string FCT_SUBCODE
	{
		get
		{
			return this._FCT_SUBCODE;
		}
		set
		{
			if ((this._FCT_SUBCODE != value))
			{
				this._FCT_SUBCODE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_NO", DbType="NVarChar(50)")]
	public string FCT_NO
	{
		get
		{
			return this._FCT_NO;
		}
		set
		{
			if ((this._FCT_NO != value))
			{
				this._FCT_NO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_CONTAINERNO", DbType="NVarChar(50)")]
	public string FCT_CONTAINERNO
	{
		get
		{
			return this._FCT_CONTAINERNO;
		}
		set
		{
			if ((this._FCT_CONTAINERNO != value))
			{
				this._FCT_CONTAINERNO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_WEIGHT", DbType="Float")]
	public System.Nullable<double> FCT_WEIGHT
	{
		get
		{
			return this._FCT_WEIGHT;
		}
		set
		{
			if ((this._FCT_WEIGHT != value))
			{
				this._FCT_WEIGHT = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_OVERHEAD", DbType="NVarChar(50)")]
	public string FCT_OVERHEAD
	{
		get
		{
			return this._FCT_OVERHEAD;
		}
		set
		{
			if ((this._FCT_OVERHEAD != value))
			{
				this._FCT_OVERHEAD = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_IMDATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> FCT_IMDATE
	{
		get
		{
			return this._FCT_IMDATE;
		}
		set
		{
			if ((this._FCT_IMDATE != value))
			{
				this._FCT_IMDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_EXDATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> FCT_EXDATE
	{
		get
		{
			return this._FCT_EXDATE;
		}
		set
		{
			if ((this._FCT_EXDATE != value))
			{
				this._FCT_EXDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_IMTIME", DbType="Time")]
	public System.Nullable<System.TimeSpan> FCT_IMTIME
	{
		get
		{
			return this._FCT_IMTIME;
		}
		set
		{
			if ((this._FCT_IMTIME != value))
			{
				this._FCT_IMTIME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_EXTIME", DbType="Time")]
	public System.Nullable<System.TimeSpan> FCT_EXTIME
	{
		get
		{
			return this._FCT_EXTIME;
		}
		set
		{
			if ((this._FCT_EXTIME != value))
			{
				this._FCT_EXTIME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_STATUS", DbType="Int")]
	public System.Nullable<int> FCT_STATUS
	{
		get
		{
			return this._FCT_STATUS;
		}
		set
		{
			if ((this._FCT_STATUS != value))
			{
				this._FCT_STATUS = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_LOADDATE", DbType="DateTime")]
	public System.Nullable<System.DateTime> FCT_LOADDATE
	{
		get
		{
			return this._FCT_LOADDATE;
		}
		set
		{
			if ((this._FCT_LOADDATE != value))
			{
				this._FCT_LOADDATE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_QNQ", DbType="NVarChar(50)")]
	public string FCT_QNQ
	{
		get
		{
			return this._FCT_QNQ;
		}
		set
		{
			if ((this._FCT_QNQ != value))
			{
				this._FCT_QNQ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_ETSNG", DbType="NVarChar(50)")]
	public string FCT_ETSNG
	{
		get
		{
			return this._FCT_ETSNG;
		}
		set
		{
			if ((this._FCT_ETSNG != value))
			{
				this._FCT_ETSNG = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RT_NAME", DbType="NVarChar(268)")]
	public string RT_NAME
	{
		get
		{
			return this._RT_NAME;
		}
		set
		{
			if ((this._RT_NAME != value))
			{
				this._RT_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME1", DbType="NVarChar(700)")]
	public string NAME1
	{
		get
		{
			return this._NAME1;
		}
		set
		{
			if ((this._NAME1 != value))
			{
				this._NAME1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(351)")]
	public string USERNAME
	{
		get
		{
			return this._USERNAME;
		}
		set
		{
			if ((this._USERNAME != value))
			{
				this._USERNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME_N", DbType="NVarChar(351)")]
	public string USERNAME_N
	{
		get
		{
			return this._USERNAME_N;
		}
		set
		{
			if ((this._USERNAME_N != value))
			{
				this._USERNAME_N = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORDER", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string BORDER
	{
		get
		{
			return this._BORDER;
		}
		set
		{
			if ((this._BORDER != value))
			{
				this._BORDER = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLC_ALLNAME", DbType="NVarChar(500)")]
	public string CLC_ALLNAME
	{
		get
		{
			return this._CLC_ALLNAME;
		}
		set
		{
			if ((this._CLC_ALLNAME != value))
			{
				this._CLC_ALLNAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(250)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this._type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS_", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string STATUS_
	{
		get
		{
			return this._STATUS_;
		}
		set
		{
			if ((this._STATUS_ != value))
			{
				this._STATUS_ = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILE1", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
	public string FILE1
	{
		get
		{
			return this._FILE1;
		}
		set
		{
			if ((this._FILE1 != value))
			{
				this._FILE1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FRM_NAME", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
	public string FRM_NAME
	{
		get
		{
			return this._FRM_NAME;
		}
		set
		{
			if ((this._FRM_NAME != value))
			{
				this._FRM_NAME = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCT_CONTROL", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
	public string FCT_CONTROL
	{
		get
		{
			return this._FCT_CONTROL;
		}
		set
		{
			if ((this._FCT_CONTROL != value))
			{
				this._FCT_CONTROL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_NAME1", DbType="NVarChar(50)")]
	public string B_NAME1
	{
		get
		{
			return this._B_NAME1;
		}
		set
		{
			if ((this._B_NAME1 != value))
			{
				this._B_NAME1 = value;
			}
		}
	}
}
#pragma warning restore 1591
